#PREDICTIONS1: VECTOR OF N PREDICTIONS (ONE DAY)
#PREDICTIONS2: VECTOR OF N PREDICTIONS (SAME DAY)
#ALPHA: PROPORTION TO TAKE FROM PREDICTIONS1

## GIVEN TWO PREDICTIONS FOR THE SAME DAY, WE TAKE THE PROPRTION ALPHA STRONGEST PREDICTIONS FROM 1,
## AND THE OTHER ONE'S FROM PREDICTIONS2. BOTH VECTORS MUST CORRESPOND TO THE SAME DAY 
## AND BE OF SAME LENGTH.
## IN THE COMBINED VECTOR, THE ONE'S EXTRACTED FROM PREDICTIONS1 WILL CORRESPOND TO THE ALPHA STRONGEST PREDICTIONS.
CombinePrediction.Day = function(Prediction1, Prediction2, alpha) {
  
  #DEFINE WHAT STOCKS TO USE FROM PREDICTIONS1
  Stocks1 = abs(Prediction1) > quantile(abs(Prediction1), 1-alpha)
  
  
  #DEFINE WHAT STOCKS TO USE FROM PREDICTIONS2
  Stocks2 = !Stocks1
  
  #CREATE A NEW VECTOR AND TAKE THE STRONGEST PREDICTIONS FROM PREDICTION1
  Prediction = numeric(length(Prediction1))
  Prediction[Stocks1] = Prediction1[Stocks1]
  Prediction[Stocks2] = Prediction2[Stocks2]
  
  
  #SCALE THE PREDICTIONS FROM FIRST PREDICTIONS SO THAT THE DECILE PORTFOLIOS ARE CONSTRUCTED FROM THESE
  #THE FOLLOWING ENSURES THAT THE MINIMUM ABSOLUTE VALUE FROM PREDICTIONS1 IS GREATER THAN THE MAXIMUM ABSOLUTE VALUE FROM PREDICTIONS2
  Prediction[Stocks1] = Prediction[Stocks1] * max(abs(Prediction[Stocks2])) / min(abs(Prediction[Stocks1])) * 1.1
  
  #RETURN
  return(Prediction)
}



###TAKES TWO MATRICES (DATA FRAMES) OF DIMENSIONS NxT WHERE EACH COLUMN CORRESPONDS TO ONE DAY'S PREDICTION.
###THEN COMBINES THE MATREICES AS PER ABOVE.

#PREDICTIONSSTRONG: THE PREDICTIONS TO EXTRACT THE STRONGEST ALPHA PROPORTION FROM
#PREDICTIONSWEAK: WHAT TO BASE THE OTHER (1-ALPHA) PREDICTIONS ON

CombinePrediction <- function(PredictionStrong, PredictionsWeak, alpha) {
  
  #LOOP THROUGH EACH COLUMN (DAY)
  #FOR EACH DAY, PERFORM CombinePrediction.Day
  CombinedPrediction = sapply(1:ncol(PredictionStrong), function(i) {
    CombinePrediction.Day(Prediction1 = PredictionStrong[, i],
                          Prediction2 = PredictionsWeak[, i], 
                          alpha = alpha) 
  })
  
  #CHANGE COLNAMES 
  colnames(CombinedPrediction) = colnames(PredictionStrong)
  
  #RETURN
  return(CombinedPrediction)
}
